name: Keep Render Site Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:        # allows manual run from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl your site
        run: curl -I https://videouploading-5ubp.onrender.com
